### ISSUE TITLE
Tylar's RStudio crashing on load

### ISSUE THREAD

**Issue by bbest** [USF-IMARS/california-coast-ecostress-biodiversity#2]
Hi @7yl4r,
I was able to knit `resolution_tests.Rmd` to `resolution_tests.html`, but the browser Preview pane was hanging because of trying to render so many obis occurrence points. I had to shutdown my RStudio session. I was able to view `resolution_tests.html` in Chrome (after a minute):

<img width="739" alt="image" src="https://user-images.githubusercontent.com/2837257/172486016-c966f74d-dc10-41a8-81f9-0fa4b347fd43.png">

I'd comment out this interactive map with too many points and try again:

```
# robis::map_leaflet(occ)
```

**Comment by 7yl4r** [comment]
Yup, that was the issue. Thanks!
